---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  connection: local
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "satya582/calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Remove Existing Container if Any
      docker_container:
        name: calculator
        state: absent
      ignore_errors: yes

    - name: Run Calculator Container
      docker_container:
        name: calculator
        image: "satya582/calculator"
        state: started
        tty: yes  # Enables terminal-like behavior
        interactive: yes  # Allows input
        detach: yes  # Runs in background but still allows interaction

